name: Build Docker Image and Push to GitHub Registry
on:
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag php74

      - name: Push Docker Image to GitHub Packages
        run: |
          echo ${{ secrets.DOCKER_REG_PAT }} | docker login ghcr.io --username ${{ github.repository_owner }} --password-stdin
          docker tag php74 ghcr.io/pjirlip/docker-php74
          docker push docker.pkg.github.com/pjirlip/docker-php74